name: Frontend
on: [push]

jobs:
  build:
    name: Build frontend image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          cd ".docker"
          docker-compose build frontend
