version: '3'

services:
  frontend:
    container_name: frontend-prod
    build:
      dockerfile: ./.docker/frontend/Dockerfile.prod
    volumes: []
    ports:
      - '80:80'

  backend:
    container_name: backend-prod
    build:
      dockerfile: ./.docker/backend/Dockerfile.prod
    volumes:
      - '../shared:/app/shared'
    ports:
      - '3000:3000'

  mongodb:
    container_name: mongodb-prod
