version: '3'

services:
  frontend:
    container_name: frontend-prod
    build:
      dockerfile: ./.docker/frontend/Dockerfile.prod
    volumes: []
    ports:
      - '80:80'

  backend:
    container_name: backend-prod
    build:
      dockerfile: ./.docker/backend/Dockerfile.prod
    volumes: []
    ports:
      - '8080:8080'

  mongodb:
    container_name: mongodb-prod
