name: Backend

on: [push, pull_request]

jobs:
  codecov-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd backend
          npm install
          npm test
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./backend/coverage/clover.xml
          flags: unittests
          name: backend
          fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build backend and mongo images
        run: |
          cd ".docker"
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build backend mongodb
