name: Frontend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build fronternd image
      run: |
        cd ".docker"
        docker-compose build frontend
