name: Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.docker/frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - '.docker/frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build fronternd image
      run: |
        cd ".docker"
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml build frontend
